const fs = require("fs");
const path = require('path');
const inquirer = require("inquirer");
const generateMarkdown = require("./utils/generateMarkdown");

// array of questions for user
const questions = [
    {type: 'input',
        message: 'What is the project called?',
        name: 'title',
        validate(answer) {
            if(!answer) {
                return "Please, fill your project name!"
            }
            return true
        }},
    {type: 'input',
        message:"Please fill in the description:",
        name: 'description',
        validate(answer) {
            if(!answer) {
                return "Please, fill in the description!"
            }
            return true
        }},
    {type: 'input',
        message: 'How do you install it?',
        name: 'installation',
        validate(answer) {
            if(!answer) {
                return "Please, fill in installation instructions!"
            }
            return true
        }},
    {type: 'input',
        message: 'How do you use it?',
        name: 'usage',
        validate(answer) {
            if(!answer) {
                return "Please, fill in how to use it!"
            }
            return true
        }},
    {type: 'list',
        message: 'What licence does it use?',
        name: 'license',
        choices: [
            "Boost",
            "ISC",
            "MIT"
        ]},
    {type: 'input',
        message: 'Are you open to contributions?',
        name: 'contributing',
        validate(answer) {
            if(!answer) {
                return "Please, fill in how to contribute!"
            }
            return true
        }},
    {type: 'input',
        message: 'What tests do you have?',
        name: 'tests',
        validate(answer) {
            if(!answer) {
                return "Please, fill in how to test!"
            }
            return true
        }},
    {type: 'input',
        message: 'What is your github username?',
        name: 'questions',
        validate(answer) {
            if(!answer) {
                return "Please, fill your github username!"
            }
            return true
        }}
];

// function to write README file
function writeToFile(fileName, data) {
    fs.writeFile(fileName, data, (err) =>
        err ? console.error(err) : console.log('Success!')
    );
}

// function to initialize program
function init() {
    let responseObj = {};
    inquirer
        .prompt(questions)

        .then((response) => {
            responseObj = response;
            response.licenseFull = getLicense(response.license);
            response.licenseBadge = badgeLicense(response.license);
            writeToFile(`readme_${response.title.replace(/ /g,"_")}.md`,generateMarkdown(responseObj));
        });
}

const licenses = {
    "Boost":`Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the “Software”) to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following:
    The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.
    THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`,

    "ISC":`Copyright <YEAR> <OWNER>
    Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
    THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.`,

    "MIT":`Copyright <YEAR><COPYRIGHT HOLDER>
    Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so.
    THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`
};

const getLicense = repLicense => licenses[repLicense];

// function to get a badge for each license
const badgeLicense = license => {
    switch (license) {
         case "Boost":
            return "[![License: IPL 1.0](https://img.shields.io/badge/License-BSL_1.0-green.svg)](https://opensource.org/license/bsl1-0-html/)";
        case "ISC":
            return "[![License: ISC](https://img.shields.io/badge/License-ISC-green.svg)](https://opensource.org/licenses/isc-license-txt/)"
        case "MIT":
            return "[![License: MIT](https://img.shields.io/badge/license-MIT-green)](https://opensource.org/licenses/mit/)";
        case "none":
            return "";
    }
}

// function call to initialize program
init();

